{{- if eq .Values.authMode "cluster" }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubetail.clusterRoleName" . }}
  labels:
    {{- include "kubetail.labels" $ | nindent 4 }}
{{- with .Values.clusterRoleBinding.rules }}
rules:
{{- toYaml . | nindent 0 }}
{{- end }}
{{- end -}}
