apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "kubetail.metadataNamespace" $ | nindent 2 }}
  name: {{ if .Values.serviceAccount.name }}{{ .Values.serviceAccount.name }}{{ else }}{{ include "kubetail.fullname" . }}{{ end }}
  labels:
    {{- include "kubetail.labels" $ | nindent 4 }}
